//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudianteUniversidad.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Universidad
    {
        public Universidad()
        {
            this.UniversidadEstudiante = new HashSet<UniversidadEstudiante>();
        }
    
        public int PK_Universidad { get; set; }
        public string Nombre { get; set; }
        public string Pais { get; set; }
        public string Ciudad { get; set; }
        public Nullable<int> AnioFundacion { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<UniversidadEstudiante> UniversidadEstudiante { get; set; }
    }
}
