//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudianteUniversidad.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversidadEstudiante
    {
        public int PK_UniversidadEstudiante { get; set; }
        public Nullable<int> FK_Universidad { get; set; }
        public Nullable<int> FK_Estudiante { get; set; }
        public bool Active { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Universidad Universidad { get; set; }
    }
}
